ACHV = [{"name": "Welcome to Hell", "desc": "Play a game"},
        {"name": "Welcome to the Asylum", "desc": "Play a chaos game"},
        {"name": "Alzheimer's Patient", "desc": "Play a game with an amnesia language pack"},
        {"name": "O HAI DER!", "desc": "Play a game with Para's secret account (not @para949)"},
        {"name": "Spy vs Spy", "desc": "Play a game in secret mode (no role reveal)"},
        {"name": "Explorer", "desc": "Play at least 2 games each in 10 different groups", "inactive":True},
        {"name": "Linguist", "desc": "Play at least 2 games each in 10 different language packs", "inactive":True},
        {"name": "I Have No Idea What I'm Doing", "desc": "Play a game in secret amnesia mode"},
        {"name": "Enochlophobia", "desc": "Play a 35 player game"},
        {"name": "Introvert", "desc": "Play a 5 player game"},
        {"name": "Naughty!", "desc": "Play a game using any NSFW language pack"},
        {"name": "Dedicated", "desc": "Play 100 games"},
        {"name": "Obsessed", "desc": "Play 1000 games"},
        {"name": "Here's Johnny!", "desc": "Get 50 kills as the serial killer", "not_via_playing":True},
        {"name": "I've Got Your Back", "desc": "Save 50 people as the Guardian Angel", "not_via_playing":True},
        {"name": "Masochist", "desc": "Win a game as the Tanner"},
        {"name": "Wobble Wobble", "desc": "Survive a game as the drunk (at least 10 players)"},
        {"name": "Inconspicuous", "desc": "In a game of 20 or more people, do not get a single lynch vote against you (and survive)"},
        {"name": "Survivalist", "desc": "Survive 100 games"},
        {"name": "Black Sheep", "desc": "Get lynched first 3 games in a row", "inactive":True},
        {"name": "Promiscuous", "desc": "As the harlot, survive a 5+ night game without staying home or visiting the same person more than once"},
        {"name": "Mason Brother", "desc": "Be one of at least two surviving masons in a game"},
        {"name": "Double Shifter", "desc": "Change roles twice in one game (cult conversion does not count)"},
        {"name": "Hey Man, Nice Shot", "desc": "As the hunter, use your dying shot to kill a wolf or serial killer"},
        {"name": "That's Why You Don't Stay Home", "desc": "As a wolf or cultist, kill or convert a harlot that stayed home"},
        {"name": "Double Vision", "desc": "Be one of two seers at the same time"},
        {"name": "Double Kill", "desc": "Be part of the Serial Killer / Hunter ending"},
        {"name": "Should Have Known", "desc": "As the Seer, reveal the Beholder"},
        {"name": "I See a Lack of Trust", "desc": "As the Seer, get lynched on the first day"},
        {"name": "Sunday Bloody Sunday", "desc": "Be one of at least 4 victims to die in a single night"},
        {"name": "Change Sides Works", "desc": "Change roles in a game, and win"},
        {"name": "Forbidden Love", "desc": "Win as a wolf / villager couple (villager, not village team)"},
        {"name": "Developer", "desc": "Have a pull request merged into the repo"},
        {"name": "The First Stone", "desc": "Be the first to cast a lynch vote 5 times in a single game"},
        {"name": "Smart Gunner", "desc": "As the Gunner, both of your bullets hit a wolf, serial killer, or cultist"},
        {"name": "Streetwise", "desc": "Find a different wolf, serial killer, or cultist 4 nights in a row as the detective"},
        {"name": "Speed Dating", "desc": "Have the bot select you as a lover (cupid failed to choose)"},
        {"name": "Even a Stopped Clock is Right Twice a Day", "desc": "As the Fool, have at least two of your visions be correct by the end of the game"},
        {"name": "So Close!", "desc": "As the Tanner, be tied for the most lynch votes"},
        {"name": "Cultist Convention", "desc": "Be one of 10 or more cultists alive at the end of a game"},
        {"name": "Self Loving", "desc": "As cupid, pick yourself as one of the lovers"},
        {"name": "Should've Said Something", "desc": "As a wolf, your pack eats your lover (first night does not count)"},
        {"name": "Tanner Overkill", "desc": "As the Tanner, have everyone (but yourself) vote to lynch you"},
        {"name": "Serial Samaritan", "desc": "As the Serial Killer, kill at least 3 wolves in single game"},
        {"name": "Cultist Fodder", "desc": "Be the cultist that is sent to attempt to convert the Cult Hunter"},
        {"name": "Lone Wolf", "desc": "In a chaos game of 10 or more people, be the only wolf - and win"},
        {"name": "Pack Hunter", "desc": "Be one of 7 living wolves at one time"},
        {"name": "Saved by the Bull(et)", "desc": "As a villager, the wolves match the number of villagers, but the game does not end because the gunner has a bullet"},
        {"name": "In for the Long Haul", "desc": "Survive for at least an hour in a single game"},
        {"name": "OH SHI-", "desc": "Kill your lover on the first night"},
        {"name": "Veteran", "desc": "Play 500 games.  You can now join @werewolfvets"}]
